global:
  api-listen-addr: :5183
  timeout: 10s
  memo: Powered by Ark Protocol
  light-cache-size: 20
  # log-level: ""
  # ics20-memo-limit: 0
  # max-receiver-size: 0
chains:
  osmosistestnet:
    type: cosmos
    value:
      key-directory: ../keys/osmo-test-5
      key: default
      chain-id: osmo-test-5
      # often testnet is highly unreliable, often this error occurs: `Internal error: transaction indexing is disabled`
      # so we need to wait for the transaction to be indexed before packets can be relayed.
      # Also RPCs for some reason dont work, `rly'' though requires port'. Rn `https://rpc.osmotest5.osmosis.zone:443` works best.
      # Also if it doesnt work, wait for a while and try again (few hours or next day...).
      rpc-addr: https://rpc.osmotest5.osmosis.zone:443 # https://rpc.osmo.test.yieldpay.finance:443 # https://rpc.osmotest5.osmosis.zone:443
      account-prefix: osmo
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01uosmo
      min-gas-amount: 0
      max-gas-amount: 0
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: 118
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []
      feegrants: null
  stargazetestnet:
    type: cosmos
    value:
      key-directory: cosmos/testnet/keys/elgafar-1
      key: default
      chain-id: elgafar-1
      rpc-addr: https://rpc.elgafar-1.stargaze-apis.com:443
      account-prefix: stars
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01ustars
      min-gas-amount: 0
      max-gas-amount: 0
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: 118
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []
      feegrants: null
paths:
  osmosistestnet-stargazetestnet:
    src:
      chain-id: osmo-test-5
      client-id: 07-tendermint-3592 # osmosis client, stargaze: 07-tendermint-932
      connection-id: connection-3157 # osmosis connection, stargaze: connection-913
    dst:
      chain-id: elgafar-1
      client-id: 07-tendermint-932 # stargaze client, osmosis: 07-tendermint-3592
      connection-id: connection-919 # stargaze connection, osmosis: connection-3157
    src-channel-filter:
      rule: allowlist
      channel-list:
        - channel-8134
        - channel-8135 # not WLed in incoming proxy
